config/routes.rb
Rails.application.routes.draw do
  
  resources :listings do 
   resources :reservations, :only => :create
  end
  
  get "/reservations" => "reservations#index"
  
  
  root to: "pages#index"
  devise_for :users, controllers: { registrations: 'registrations' }
  
  resources :users,only:[:show]
  
  resources :listings do 
   resources :reviews, only:[:create,:destroy]
  end

  
  get 'manage-listing/:id/basics' => 'listings#basics', as: 'manage_listing_basics'
  get 'manage-listing/:id/description' => 'listings#description', as: 'manage_listing_description'
  get 'manage-listing/:id/address' => 'listings#address', as: 'manage_listing_address'
  get 'manage-listing/:id/price' => 'listings#price', as: 'manage_listing_price'
  get 'manage-listing/:id/photos' => 'listings#photos', as: 'manage_listing_photos'
  get 'manage-listing/:id/calendar' => 'listings#calendar', as: 'manage_listing_calendar'
  get 'manage-listing/:id/bankaccount' => 'listings#bankaccount', as: 'manage_listing_bankaccount'
  get 'manage-listing/:id/publish' => 'listings#publish', as: 'manage_listing_publish'
  
  
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :reservations
  has_many :reviews
  
  validates :home_type,presence:true
  validates :pet_type,presence:true
  validates :pet_size,presence:true
  validates :breeding_years,presence:true
  
  has_attached_file :image, styles: { medium: "700x500#", small: "350x250>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  
  
  geocoded_by :address
  after_validation :geocode,:if => :address_changed? 
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :listing
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :listing
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :listings
  has_many :reservations
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:name,:email,:phone_number,:description])
  end


end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_listing, only: [:show,:update, :basics, :description, :address, :price, :photos, :calendar, :bankaccount, :publish]
  
  def index
    @listings = current_user.listings.all
  end

  def show
    @reviews = @listing.reviews
  end

  def new
    @listing = current_user.listings.new
  end

  def create
    @listing = current_user.listings.new(listing_params)
    if @listing.save
      redirect_to manage_listing_basics_path(@listing),notice:"リスティングを作成・保存しました"
    else 
      render new_listing_path(@listing),notice:"リスティングを作成・保存できませんでした"
    end
  end

  def edit
  end

  def update
    if @listing.update(listing_params)
      redirect_back(fallback_location: root_path)
    end
  end
  
  def basics
  end
  
  def description
  end
  
  def address
  end

  def price
  end

  def photos
  end

  def calendar
  end

  def bankaccount
  end

  def publish
  end
  
  private
  
    def set_listing
      @listing = Listing.find(params[:id]) 
    end
  
    def listing_params
      params.require(:listing).permit(:home_type,:pet_type,:pet_size,:breeding_years,:price_pernight,:address,:listing_title,:listing_content,:action,:image)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  
  def index
    @reservations = current_user.reservations
  end
    
  
  def create
    @reservation = current_user.reservations.create(reservation_params)
    redirect_to @reservation.listing , notice:"予約が完了しました"
  end
  
  private
  
    def reservation_params
      params.require(:reservation).permit(:start_date,:end_date,:price_pernight,:total_price,:listing_id)
    end
  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
      @review = current_user.reviews.create(review_params)
      redirect_to @review.listing
  end
  
  def destroy
      @review = Review.find(params[:id])
      @review.destroy
      
      redirect_to @review.listing
  end
  
  private
      def review_params
          params.require(:review).permit(:description, :rate ,:listing_id)
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
      @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pets</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <ul>
          <li><a href="/">ホーム</a></li>
      <% if user_signed_in? %>
          <li><%= link_to "#{current_user.email.split("@")[0]}さんのプロフィール",user_path(current_user) %></li>
          <li><%= link_to "シッターになる",new_listing_path %></li>
          <li><%= link_to "リスティング管理",listings_path %></li>
          <li><%= link_to "アカウント編集",edit_user_registration_path %></li>
          <li><%= link_to "ログアウト",destroy_user_session_path,method: :delete %></li>
      <% else %>
          <li><a href="#">利用の流れ</a></li>
          <li><%= link_to "シッターになる",new_listing_path %></li>
          <li><%= link_to "アカウント作成",new_user_registration_path %></li>
          <li><%= link_to "ログイン",new_user_session_path %></li>
      <% end %>
    </ul>
    

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_for @listing do |f| %>
  <p><%= f.label "お家の種類" %>
  <%= f.select :home_type, [["一軒家","一軒家"], ["マンション","マンション"], ["アパート","アパート"]], 
  {prompt:"選択してください"}, {required: 'true', autofocus: 'true', class: 'form-control'} %>
  
  <p><%= f.label "ペットの種類" %>
  <%= f.select :pet_type, [["犬","犬"], ["猫","猫"], ["鳥類","鳥類"], ["爬虫類","爬虫類"], ["魚類","魚類"], ["両生類","両生類"], ["その他","その他"]], 
  {prompt:"選択してください"}, {required: 'true', autofocus: 'true'} %>
  
  <p><%= f.label "ペットの飼育歴" %>
  <%= f.select :breeding_years, [["1年",1], ["2年",2], ["3年",3], ["4年",4], ["5年",5], ["6年以上",6]], {prompt:"選択してください"}, 
  {required: 'true', autofocus: 'true'} %>
  
  <p><%= f.label "ペットのサイズ" %>
  <%= f.select :pet_size, [["小型","小型"], ["中型","中型"], ["大型","大型"], ["超大型","超大型"]], {prompt:"選択してください"}, 
  {required: 'true', autofocus: 'true', class: 'form-control'} %>
  
  <p><%= f.submit "保存" %>
<% end %>

app/views/listings/_varnab.html.erb
-----------------------------------
<ul>
<li><%= link_to "基本事項",manage_listing_basics_path(@listing) %></li>
<li><%= link_to "リスティングの内容住所情報",manage_listing_description_path(@listing) %></li>
<li><%= link_to "住所情報", manage_listing_address_path(@listing)%></li>
<li><%= link_to "料金", manage_listing_price_path(@listing) %></li>
<li><%= link_to "写真", manage_listing_photos_path(@listing) %></li>
<li><%= link_to "カレンダー", manage_listing_calendar_path(@listing)  %></li>
<li><%= link_to "受取口座情報", manage_listing_bankaccount_path(@listing) %></li>
<li><%= link_to "公開する",  manage_listing_publish_path(@listing) %></li>
</ul>
-----------------------------------

app/views/listings/address.html.erb
<%= render "listings/varnab" %>

<%= form_for @listing do |f| %>
  <p><%= f.label "住所" %>
  <%= f.text_field :address, placeholder: "例: 東京都港区六本木６丁目１１−１", class: "form-control" %>
  
  <p><%= f.submit "更新" %>
<% end %>

app/views/listings/bankaccount.html.erb
<%= render "listings/varnab" %>

<%= form_for @listing do |f| %>
  <p><%= f.label "口座" %>
  <%= f.text_field :price_pernight, placeholder: "例: 100", class: "form-control" %>
  
  <p><%= f.submit "更新" %>
<% end %>

app/views/listings/basics.html.erb
<h1>基本データの編集</h1>
<%= render "listings/varnab" %>
<%= render "listings/form" %>

app/views/listings/calendar.html.erb
<%= render "listings/varnab" %>


<%= form_for [@listing, @listing.reservations.new ] do |f| %>
  <p><%= f.label "カレンダー" %>
  <%= f.hidden_field :listing_id, value:@listing.id %>
  
  <p><%= f.submit "更新" %>
<% end %>

app/views/listings/create.html.erb
<h1>Listings#create</h1>
<p>Find me in app/views/listings/create.html.erb</p>

app/views/listings/description.html.erb
<%= form_for @listing do |f| %>
  <p><%= f.label "タイトル" %>
  <%= f.text_field :listing_title,placeholder:"リスティングタイトルを記載しましょう" %>
  
  <p><%= f.label "内容" %>
  <%= f.text_area :listing_content,placeholder:"リスティングの内容につdevelopmentいて記述してください" %>
  
  <p><%= f.submit "更新" %>
<% end %>

app/views/listings/index.html.erb
<h1><%= current_user.name %>さんのリスティング一覧</h1>

<% @listings.each do |listing| %>
----------------------------
<p><%= image_tag listing.image(:small) %>
<p><%= listing.listing_title %>
<p><%= link_to "残り5ステップ",manage_listing_basics_path(listing) %><br>
<% end %>

app/views/listings/new.html.erb
<h1>リスティング作成</h1>
<%= render "listings/form" %>

app/views/listings/price.html.erb
<%= render "listings/varnab" %>

<%= form_for @listing do |f| %>
  <p><%= f.label "一泊あたりの料金" %>
  <%= f.text_field :price_pernight, placeholder: "例: 100", class: "form-control" %>
  
  <p><%= f.submit "更新" %>
<% end %>

app/views/listings/publish.html.erb
<%= render "listings/varnab" %>

<%= form_for @listing do |f| %>
  <p><%= f.label "公開/非公開" %>
  <%= f.select :action, [["公開する","true"], ["非公開にする","false"]], {prompt:"選択してください"}, {required: 'true', autofocus: 'true', class: 'form-control'} %>

  <p><%= f.submit "更新" %>
<% end %>

app/views/listings/show.html.erb
<h1>リスティング詳細</h1>
<p><%= @listing.home_type %>
<p><%= @listing.pet_size %>
<p><%= @listing.breeding_years %>
<p><%= @listing.address %>
<p><%= @listing.listing_title %>
<p><%= @listing.listing_content %>
<p><%= @listing.price_pernight %>
<p><%= @listing.action %>
<p><%= @listing.image %>
<p>---------------------------------<br>
<p><%= link_to @listing.user.name,user_path(@listing.user) %>


<p>---------------------------------<br>
<p>
    <% if @listing.price_pernight.blank? %>
     <h2>値段が設定されていません
    <% else %>
    <%= @listing.price_pernight %> 円（一晩あたり）
    <% end %>
<!--/listings/:listing_id/reservations(.:format)のうち、第一引数で:listing_idを指定し、第二引数で新しく作られたreservations,を@listing.reservations.newで指定している。-->
<%= form_for [@listing, @listing.reservations.new ] do |f| %>

<!--この三つが一緒に送られる-->
<%= f.hidden_field :listing_id, value:@listing.id %>
<%= f.hidden_field :price_pernight, value:@listing.price_pernight %>
<%= f.hidden_field :total_price, value:@listing.id %>


<%= f.text_field :start_date, :placeholder => "開始" %>
<%= f.text_field :end_date, :placeholder => "終了" %>


<%= f.submit "この日程で予約する", class: "btn btn-danger btn-wide" %>
<% end %>

<p>---------------------------------<br>
<h2>レビュー（<%= @reviews.count %>）</h2>
<p>---------------------------------<br>

<%= render "reviews/form" %>
<%= render "reviews/list" %>

<h2>近くのリスティング</h2>

<% for listing in @listing.nearbys(10) %>
<p>---------------------------------<br>
<p><%= link_to listing.listing_title, listing %>
<p><%= link_to listing.address, listing_path(listing) %>
<p></p><%= link_to listing.user.name,user_path(listing.user) %>
<% end %>

app/views/listings/update.html.erb
<h1>Listings#update</h1>
<p>Find me in app/views/listings/update.html.erb</p>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/reservations/index.html.erb
<% @reservations.each do |reservation| %>
<p>----------------------------------<br>
<%= reservation.listing.id %><br>
<%= reservation.listing.created_at %><br>
<%= reservation.listing.user.name %><br>
<% end %>

app/views/reviews/_form.html.erb
<%= form_for([@listing,@listing.reviews.new]) do |f| %>
<%= f.text_area :description %>
<%= f.hidden_field :listing_id,value: @listing.id %>
<%= f.submit "このシッターを評価する" %>
<% end %>

app/views/reviews/_list.html.erb
<% if @reviews.count == 0 %>
<h4>レビューはありません</h4>
<% else %>
 <% @reviews.order("id desc").each do |review| %>
     <p>-------------------------</br>
     <%= review.user.email %>さんのレビュー
     <%= review.description %>
     <%= review.created_at %>
     <%= link_to "削除する",[@listing,review],method: :delete, data: {confirm:"削除しますか？"} if current_user && current_user == review.user %>
 <% end %>
<% end %>

app/views/users/show.html.erb
<h1 id="var-name">名前：<%= @user.name%></h1>
<h1 id="var-email">メールアドレス：<%= @user.email%></h1>
<h1 id="var-phone_number">電話番号：<%= @user.phone_number %></h1>
<h1 id="var-description">自己紹介：<%= @user.description%></h1>